### ISSUE TITLE
UX new layout proposition

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#110]
Let me introduce a small mockups (sorry but I'm not good drawer:D) which in my perception would be nice improvement and give a bit of structuration.

Let's start with main page (dashboard) where we will see main system status and recent jobs (and on the other hand this will give us entrypoint to more detailed pages like minions, keys, jobs):
![dashboard-1](https://user-images.githubusercontent.com/5910851/50516313-682cdf00-0aaa-11e9-829b-c497a8f45eb6.png)

If we will click to minion status graph or pickup the minions upper link we will be routed to minions information page (this page will be main starting point to interact with particular minion):
![minions](https://user-images.githubusercontent.com/5910851/50516342-9c080480-0aaa-11e9-9b69-06ff9e8b4b5d.png)

If we will click to keys status graph or pickup the keys upper link we will be routed to keys information page (this page will be main point to interact with minion keys):
![keys](https://user-images.githubusercontent.com/5910851/50516411-fa34e780-0aaa-11e9-996b-f4f26d9cae5f.png)

If we will click to jobs status graph or pickup the jobs upper link we will be routed to jobs information page (this page will be main point to check status and output of particular job):
![jobs](https://user-images.githubusercontent.com/5910851/50516466-42eca080-0aab-11e9-90a2-7d6454bb3397.png)

I'm open for discussion and propositions how we could go forward with such change. I would be also interested how we could make this pages looks more beautiful and respectieve (be compatibile with mobile devices) and use bootstrap opensource templates for example but keep the page as simple and clean as possible.

**Comment by erwindon** [comment]
Impressive!

Note that `runner.jobs.list_jobs` (which provides the job list) does not tell anything about the outcome of the jobs in the list. `runner.jobs.active` returns the list of running jobs with only an indication on how many of the targeted minions for each job have completed. Only `runner.jobs.list_job` provides all details about the outcome of a job, but that one must be called per job. Is everything you propose possible with the implementation of these commands?

The previous project owners were very conservative with the introduction of additional libraries. Mainly due to license issues that would restrict their freedom. I will look at that too in a similar way.

This is a big project, at least when compared to the available time. And I still have some other work on SaltGUI that I want to do also, some of it you are already involved. Your proposal should be broken down into individual changes, which can be handled separately in individual PRs. Not necessarily all at once. Please do not be disappointed when this takes a long time or when I do not accept all parts.

**Comment by dawidmalina** [comment]
Thank for your support and I fully understand your point of view. Hopefully we can do as much as we can:)

**Comment by dawidmalina** [comment]
You are right we can't get all jobs details in one shot. So my proposition (let's start with recent jobs) focus only on last 10 jobs and fetch for them all data to have real status of the jobs. If you don't mind I would create dedicated ticket for this.

**Comment by dawidmalina** [comment]
If you are interested I started prototyping modified layout for SaltGUI which will satisfy my needs. You can check my fork (branch: malina-v2). Maybe some parts (someday) could be backported if you find them valuable but for now I will stick with my own repo.

**Comment by erwindon** [comment]
Again impressive.
I will not pull in that branch as a whole, but I will certainly use several/many elements of it.
e.g. the use of ☰ is convincing.
(but not the animated command box, too much movement for me...)
Please note that SaltGUI has an adaption for small screens using `@media (max-width: 800px)`. In that case the menu bar is displayed as a single drop-down menu.

**Comment by dawidmalina** [comment]
For animated command box I know it's fancy ;) but I have some idea. If we could change the layout and make it looks like regular page but keep it as is. Then we could have consistent pages but still benefit from current feature where you want to go back to the location where you've initiated the navigation to the command page when you click close button. If you are interested I can drop a pull request.

If you could also tell me whether you are interested in table layout proposition from my branch then I can also drop a pull request.

I respect your requirement that you want to support small screens but if you could consider to remove recent jobs box and introduce dedicated page for all jobs, then I don't see issue with small width. I can also drop a pull request.

Rest of changes from my branch can be disused separately. Are you using saltstackcommunity.slack.com? This could be nice improvement to discussion f2f.

**Comment by erwindon** [comment]
I've talked about making the command-box a separate page with the previous project owner (maerteijn). Never really finished that. From a GUI point-of-view a popup window makes sense. A lot of menu options are just simply pre-filling the command-box. So it makes sense to return to the original page after executing the command. Which is of course very efficient due to just hiding a layer. Otherwise a more complex page history must be maintained and a page-reload will happen when returning.

I'm not using saltstackcommunity.slack.com (yet).

The jobs list should indeed move to its own page. And then of course in a regular table format like you showed. Note that the Target and Arguments column can become very wide.

So far I noticed the following other updates (with my first reaction):
* sorting indicator has become small arrow --> ok
* improved dropdown menu styling --> ok
* font-face+font-color has changed --> neutral
* run-button has become normal menu item --> ok
* table row is highlighted on mouseover --> nothing is selected, so this is only cosmetic?
* run-command (accidentally?) uses new proportional font --> monospace is still preferred, also for text layout issues
* new menubar --> looks good, dropdown menus from bar have divider line that menus from dropdown icon do not have. ok when regular dropdown menu returns for small screens
* os-icons are reduced size --> I liked them in the original size
What else did I miss?

let's do this one-by-one...

**Comment by dawidmalina** [comment]
I've created pull request https://github.com/erwindon/SaltGUI/pull/136 for basic changes. Next step (after merge) I will start work on menubar improvements and dedicated jobs page.

**Comment by erwindon** [comment]
@dawidmalina , can you give a short summary of the individual changes that you propose for this issues?

**Comment by dawidmalina** [comment]
For now this is the full list of ui changes that I would like to have:
- [x] sorting indicator has become small arrow
- [x] improved drop down menu styling
- [x] dedicated jobs page
- [x] dedicated templates page
- [ ] list more jobs (more then 20) on jobs page with pagination
- [ ] run-button can become normal menu item
- [ ] table row is highlighted on mouseover
- [ ] new top menu with drop down items (minions -> grains, schedulers, pillars and jobs -> templates)
- [ ] new keys page content
- [ ] dedicated minion status column (as currently status offline is mixed with ip)
- [ ] rerun job from jobs page
- [ ] move run command popup to dedicated page

**Comment by erwindon** [comment]
Is everything covered properly in other issues? if so, I will close this issue...

**Comment by dawidmalina** [comment]
Yes we can close this issue.
