### ISSUE TITLE
add ability to rerun the job

### ISSUE THREAD

**Issue by dawidmalina** [erwindon/SaltGUI#141]
I would be nice if we could rerun the particular job.

**Comment by erwindon** [comment]
First regular re-run should be added.
Its action is based on the output from `jobs.list_jobs`, which we already have.
The function opens the commandbox pre-filled with the old values.
`Function`+`Arguments` should be placed the the command field as valid commandline with json arguments. Preferably simple strings become un-quoted.
`Target-type` should be used to pre-select the target type when it is one of the 4 known targettypes. Otherwise the targettype becomes `automatic`.
`Target` should be used to pre-fill the target field.
`StartTime`+`User` are not used.

**Comment by dawidmalina** [comment]
There is also one issue as currently returned tergettype is unknown (https://github.com/erwindon/SaltGUI/issues/103). So users with wrong salt version will be affected by this bug.

Another small challenge will be with arguments as sometimes it can be empty, string or object (even if argument was provided as string).
