### ISSUE TITLE
deactivate refresh on Minion-Mainpage

### ISSUE THREAD

**Issue by Meiglus** [erwindon/SaltGUI#179]
Hi, 

is there any possibility to deactivate the refresh on the minion mainpage? We faced the issue, that after some refreshs of the mainpage some of our (windows)server overloaded due to 5-6 phyton processes. I guess it was the request vor the version and the OS stuff.

Is there any possibility to build a workaround for that? Maybe that's something other users might have, too. 

Thanks in advance,
Michael

**Comment by erwindon** [comment]
@Meiglus 
The grains-information in columns Status, SaltVersion and OsVersion are not collected separately. That information is available because we fire a `grains.items` command to figure out which minions are reachable.
Some pages use an other command, but the effect is the same.
50% of my minions are on Windows too, but I do not have similar problems.
Which versions of the Salt Minions are you using?

**Comment by Meiglus** [comment]
Hi @erwindon ,

thanks for your quick reply!

To test the GUI I implemented a lot of our servers and hit the "minions" button a few times to check out the behaviour. 

![image](https://user-images.githubusercontent.com/38916398/52556272-6619a800-2dec-11e9-9bb9-bf781477ebbb.png)

And soon after that we experienced high load on some servers. I checked the logfile, but couldn't find something interesting. A colleague of mine just said to me that there were a lot of phyton processes and ofter some minutes they were gone and the server was stable again. 

We use the 2018.3.0 at the moment.

**Comment by erwindon** [comment]
@Meiglus 
yes, the Windows minions are known to be much less efficient.
I see no quick solution to organize so that SaltGUI produces even less commands for the minions.

We have some aces up our sleeves:
- caching more information (and take the risk that the screen lags behind)
- defining worksets to involve less minions
- starting SaltGui directly with the screen that you want to use
- etc.
So far this was not needed, so we are not working on it.
Feel free to suggest a feature that may help you...

**Comment by erwindon** [comment]
see #181
