### ISSUE TITLE
Filter out running jobs

### ISSUE THREAD

**Issue by elipsion** [erwindon/SaltGUI#222]
**Is your feature request related to a problem? Please describe.**
I manage a large host of salt minions (~250). I have a hard time finding jobs that are still running.

**Describe the solution you'd like**
Being able to filter jobs (primarily running state; but also operation (i.e. `state.highstate`), and target (specific minion or `*`)

**Describe alternatives you've considered**
Manually running `saltutil.running` through the SaltGUI CLI.

**Comment by elipsion** [comment]
My jobs tab is mainly filled with scheduled `grains_refresh` and `mine.update`. I'm not sure if those really are interesting to anybody. Maybe they should be hidden by default?

**Comment by erwindon** [comment]
@elipsion 
You can sort the table by clicking its column header so that the running jobs are sorted to the top of the table.

Additionally, on branch "search", I'm introducing a generic text filter. Type some text in the filter field, and only the rows that are somehow matching are displayed. It will be just a few days before I merge it in. Just type "running" in the field when on the `Jobs` page and typically only the running jobs remain.

Now that I think of it, I see room for a "quick-filter" option:
* on Jobs page, show only running jobs
* on Keys page, show only unaccepted keys
* any more?
I'll fit that in later...

**Comment by erwindon** [comment]
> My jobs tab is mainly filled with scheduled `grains_refresh` and `mine.update`. I'm not sure if those really are interesting to anybody. Maybe they should be hidden by default?

Currently we are only hiding the commands that SaltGUI uses internally, or the commands that it proposes to the user. I'll take this as a request to further reduce the list, by means of configuration in the `master` file.

Can you please re-enter your original remark on this subject as a separate issues?
(and please do NOT reply on this message here)

**Comment by elipsion** [comment]
> You can sort the table by clicking its column header so that the running jobs are sorted to the top of the table.

Indeed you can, but the list seems to be capped at 50 entries, leaving stray jobs (that can be running for days) out of the table to be sorted.

**Comment by dawidmalina** [comment]
I think that having additional indicators to jobs list would be really interesting. For now I am thinking of (kind of checkboxes):
- active
- failed
- succeeded

Having this you could see active jobs or all failed jobs or combination of selected items.

**Comment by erwindon** [comment]
@elipsion another feature in this area (sorting/filtering) is present as #221, any comment is welcome!

**Comment by erwindon** [comment]
I'll work on 2 separate features:
1) the jobs listing(s) will be limited on-screen only. a better indication will be given on what is shown. e.g. "7 jobs shown, 20 jobs hidden, 123 more jobs known".
2) the filter facility will be updated to make it easier to filter for active jobs, unaccepted keys, etc. failed/succeeded jobs is still not possible because there is no proper api function for that.

**Comment by erwindon** [comment]
Part 1 is ready.
All pages now list the amount of records that they are showing. The JOBS page shows how many could have been shown without the filter on the maximum number of rows. And it shows how many could have been shown without any filter. A dropdown menu is added to select between the 3 available selections.

**Comment by erwindon** [comment]
Part 2 is also ready.
The text field that is used for filtering now has list-of-values to make entry of standard words like "accepted" or "running" a bit easier.

**Comment by erwindon** [comment]
@elipsion Can you please close this issue when you feel that this is an acceptable solution for your question? And if not, tell what is still wrong or missing...

**Comment by erwindon** [comment]
@elipsion 
After about 2 weeks, we assume that you have no problems with this solution...
Feel free to submit followup issues when you have them!
thx
Erwin
