### ISSUE TITLE
Job output page is not filterable

### ISSUE THREAD

**Issue by elipsion** [erwindon/SaltGUI#233]
**Is your feature request related to a problem? Please describe.**
It's hard to read the job output page when it's printed as blocks of text.

**Describe the solution you'd like**
I'd like to be able to filter (and possibly sort) the job output on values like `node`, `changes`, and `result`.

**Describe alternatives you've considered**
Pasting the raw JSON output into `jq` and filtering the results that way.

**Additional context**
There's also a lot of dead space on the job output. A tabular format might be better at increasing information density.

**Comment by erwindon** [comment]
@elipsion very useful suggestion!

**Comment by erwindon** [comment]
For this issues, I'll only consider the filtering of the output. Sorting and reformatting can become different issues when you want. Just create them.

**Comment by erwindon** [comment]
Filtering can be done on 2 levels:
1) per minion
2) per task of a highstate job
Let's automatically apply any search to the tasks instead of the minions when the output is a highstate output. When no tasks are left to show, the minion is hidden too.

Searching can be done in 2 ways:
1) simple text search
2) condition search for minion: no-response/success/failure/busy/etc; and also per task: success/failure/changes/etc.
Let's first build a text search. Just search for terms like "no response", "success = false", "exitcode =". Such terms can be in a dropdown box on the search box (see Keys page for an example)

Note that in none of scenario's the dropdown menu changes functionality. "Re-run job on all minions" uses the original list of minions, not the filtered list.

**Comment by erwindon** [comment]
A first implementation is available in branch `outputfilter`. It is agnostic about the structure of the actual output. It just hides all DIVs that do not have a matching text. So no logic for highstate was actually needed.
The previous search implementation was highly focussed (read "hard-coded") for tables. A copy has been taken from that for the new search capability.

**Comment by erwindon** [comment]
Limited the number of highlighted strings to 25. Otherwise ridiculous things happen when the use types e.g. `e` in a big output. The actual search function continues beyond that.

**Comment by erwindon** [comment]
merged
