### ISSUE TITLE
A highly condensed job report

### ISSUE THREAD

**Issue by elipsion** [erwindon/SaltGUI#234]
**Is your feature request related to a problem? Please describe.**
When running highstate on a lot of minions, it's hard to find the states that failed or resulted in changes.

**Describe the solution you'd like**
I'd like to have a ~10px high line, divided into chunks, one per statement, colour coded by the result of each. Hovering over or clicking on a chunk should display a reasonable amount of information, like what changed or stdout/stderr, preferably without navigating away from the listing.

**Describe alternatives you've considered**
In the case that actual graphics prove too complicated, a more HTML-oriented approach are totally fine, like a 1-row table or simply different ASCII-characters like `. ~ !` for `OK change error`. The important part is the ease of finding errors in a sea of changes or no-ops.

**Additional context**
It's probably a good thing to order the state results in execution order, as this will make it easier to spot patterns on several minions.

**Comment by erwindon** [comment]
@elipsion interesting idea!
Where should this bar roughly be shown?
For now I am assuming:
* within the job output (either the run-output, or job-output); and
* only for minions that returned a highstate result; and
* only for the minions that are collapsed (just collapse-all to see all graphical summaries).

4 colours will be used:
* dark-green: all ok
* bright-green: all ok but there were changes
* yellow: all ok, but the state was skipped/test-mode
* red: state failed

The output will be in a (saltgui-)standard tooltip. Let's see whether the original html can be put in there too. Then all the details are again present. Otherwise it'll have to be a small summary of state-id, function name and the number or changes. 

Some backporting must be done to apply the same 4 colours/styles to the regular output. It currently separates only in 3 categories.

**Comment by elipsion** [comment]
Here's a mock-up of how it could look, made in Excel: 
![image](https://user-images.githubusercontent.com/714809/59198067-28a70a80-8b93-11e9-91d3-0a97827e0d82.png)
The idea is to make it super easy to find and drill down into errors in a somewhat large fleet of minions/states.

**Comment by erwindon** [comment]
The good news is that I understood your original request :-)

The main problem is that you describe a 4-level interaction model:
* "one-line-per-minion" as seen with node1..node3
* "one-line-per-state" as seen with node 4, state1..state3
* "summary-per-state" as seen with node 4, failstate2
* "full-details" when showing all details as in the original output
I'm afraid the interaction model becomes too complex to support all that :-(

The interaction design is now:
* a list of bullets (●●●●●●●●●●●●) with the appropriate colours will be added for each minion that returned highstate data
* an information bubble will be added to each bullet (●). It is shown when the mouse hovers the bullet. The information shows state-id, function name, the number or changes (when>0) and finally the retcode info. Due to problems with long text here, I'll leave it at this for now.
* clicking on a bullet (●) makes the minion results visible when they were still hidden. it also scrolls the screen to make the details visible when they would otherwise be below the end of the screen.

After all this, we'll see what more can be done to make it even better.

**Comment by erwindon** [comment]
html demo:
![afbeelding](https://user-images.githubusercontent.com/3663742/59234167-ccbca000-8beb-11e9-8358-e297af129dd1.png)

**Comment by erwindon** [comment]
What is the maximum amount of tasks per minion in your systems?

**Comment by erwindon** [comment]
@elipsion 
What is the (estimated) maximum amount of tasks per minion in your systems?

**Comment by elipsion** [comment]
Looking awesome!

Our base configuration clocks in at 86 states as of today, with a complicated configuration running at 175. The last `salt * highstate` applied to 246 minions, for a total about 23'000 individual statements.

**Comment by erwindon** [comment]
@elipsion 
175 of these characters still fit on one line, at least on my 24" 1920x1080 screen, when simulated.
I've committed the new code on a new branch `hlstatus`.
Can you have a look at it?
The features are:
* extra info is shown behind each minion name with a summary of the tasks of a highstate job
* the colours green/yellow/red are used and match the indicators for the tasks
* successful tasks with changes get a double overline+underline to mark them
* a tooltip is available for each summary character with identifying information. in #235, the styling of the tooltip will be adjusted.
* clicking on a summary character scrolls the screen to the corresponding task details (too bad if that is hidden). the task is highlighted for 1 second for easy identification.
let me know where there should be changes...

**Comment by elipsion** [comment]
Super nice! 😄 
![image](https://user-images.githubusercontent.com/714809/59333270-49d53b80-8cf8-11e9-8287-515ae1e35cf9.png)
The memory usage is a tad on the high side, but I guess that's to be expected when stuffing 15MB of JSON down the throat of a browser. Please contact me if you want an example `list_job`-JSON for testing.

**Comment by erwindon** [comment]
@elipsion no need for more input data. thx for the great idea!
@rgroux thx for the thumbs-up!
I've added a small extra feature: clicking on any minion output scrolls the screen back to the summary line. I found that useful when investigating multiple tasks of one minion.
And I noticed a small issue: failed task do not report the number of changes. The handling of status and changes is now separated. this means that also red circles can have the changes-marker.
Can you again please have a look at it? and revert this issue back to me when you are done?

**Comment by elipsion** [comment]
Those changes feel useful, nice!
I feel that clicking on a summary bullet should also expand a minion if necessary, having to move the mouse over to the left and then back again to the tiny dot is a little annoying after the first few times.
@erwindon I seem to lack the power of assigning the issue back to you.

**Comment by erwindon** [comment]
I completely agree with you. I'll include it.
And should it be collapsed when one returns to the summary bar (by clicking anywhere on the content)?

**Comment by erwindon** [comment]
@elipsion 
The host-block is now opened when you click on one of the summary symbols.
Can you again please have a look at it? and tell me when you are done?

**Comment by erwindon** [comment]
Note that branch `hlstatus` has been rebased and is now a child-branch of `tooltip` (see #235)

**Comment by elipsion** [comment]
> [...] should it be collapsed when one returns to the summary bar [...]?
My gut feeling is that it would be confusing for the user, they'd loose the context of which host was being worked on.

**Comment by elipsion** [comment]
There seems to be a bug related to the generation of div-IDs, all divs on some hosts get the same ID.
![image](https://user-images.githubusercontent.com/714809/59493935-59858900-8e8c-11e9-849a-d7852bb94f36.png)

**Comment by erwindon** [comment]
The IDs are generated from the minion-id and the field `__id__` of the task. In this case the `__id__` is `undefined` each time. The tooltips on the summary bullets should also show that.
I don't see that behaviour with my 625 tasks.
Can you please share the raw output from salt for one task that has that behaviour?

**Comment by erwindon** [comment]
fixed a bug: the task navigation did not properly restrict the scope. this had conflicts with elements on other pages. most notable: job page vs run popup page.

**Comment by erwindon** [comment]
I'm looking for an alternative for "click to return to top" because that interferes with selecting the output text...

**Comment by erwindon** [comment]
merged
