### ISSUE TITLE
Dynamic rendering of job output

### ISSUE THREAD

**Issue by elipsion** [erwindon/SaltGUI#236]
**Is your feature request related to a problem? Please describe.**
When viewing the job output page for a large number of states, the loading times are painfully slow.

**Describe the solution you'd like**
That as much as possible of the page be kept out of the DOM until they are requested by and displayed to the user.

**Describe alternatives you've considered**
Waiting.

**Additional context**
With the changes introduced in #234, most of the elements on the job output page can be hidden and unloaded by default. Only when expanding a minion should the respective elements be calculated and put into the page. The tool tips are only shown one at a time, so keeping them all in the DOM is also wasteful.

**Comment by erwindon** [comment]
> The tool tips are only shown one at a time, so keeping them all in the DOM is also wasteful.
Can you create a separate issue for that?

**Comment by elipsion** [comment]
Done! See #240

**Comment by erwindon** [comment]
@elipsion 
My proposal would be to turn a HTML section to a single string (using `node.innerHTML`) and removing the original nodes when collapsing a section. The summary (●●●●) would always be visible, even though each "●" is actually a `span`.
When more than X minions (e.g. 50) are shown, the default output changes to the "collapsed" state, instead of the "open" state. This way output for one/few nodes is still immediately visible; and output for many nodes is compressed.
Unfortunately, this is not compatible with the search function that was also added recently. So collapsed nodes will no longer found.
What do you think?

**Comment by elipsion** [comment]
I'd say it's reasonable to only trigger the compressed state on some ("large") number of nodes.

I see two ways of dealing with the search field:
* Using the search field could trigger the expansion-function, and expand all nodes. Probably easier.
* Search could be executed on the parsed data from `salt-api`, and the relevant nodes expanded. Probably harder, but much sleeker, imho.

**Comment by erwindon** [comment]
I'll try to set this up.
But note that it will have a slightly lower priority, sorry.
Some small issues (usually cosmetic) keep popping up.
I want to squash these and the other open issues first.

**Comment by erwindon** [comment]
> When more than X minions (e.g. 50) are shown, the default output changes to the "collapsed" state, instead of the "open" state.
done

(reducing html for collapsed parts: not done yet)

**Comment by erwindon** [comment]
I did not find any solution that would keep the search function working and at the same time produce less html output. Hopefully Moore's law and the progress of browser technology have helped enough in the meantime.
Everyone: feel free to propose individual optimizations (in a new request) when you spot an opportunity for that.
