### ISSUE TITLE
Dynamic rendering of tool tips

### ISSUE THREAD

**Issue by elipsion** [erwindon/SaltGUI#240]
**Is your feature request related to a problem? Please describe.**
When viewing pages with lots of tool tips, the experience is unnecessarily slow.

**Describe the solution you'd like**
For the tool-tip-element to be rendered on the fly as needed.

**Describe alternatives you've considered**
Having a single tool-tip-element that is moved around and hidden/shown as needed.

**Additional context**
 The tool tips are only shown one at a time, so keeping them all in the DOM is kind of wasteful.

**Comment by erwindon** [comment]
(a had a vision that this request was coming...)
I've created a first implementation in branch `tooltip2`.
You need to update the `master` file so that SaltGUI chooses a simpler format for the tooltips.
The `master` file is read just after login.
The tooltips can even be switched off completely.
Since the simpler format is the browser native format, timing and format can no longer be controlled.
Can you please measure the speed-up (if any) between the 3 available formats?

**Comment by erwindon** [comment]
merged
