### ISSUE TITLE
Support salt-run commands for orchestrators

### ISSUE THREAD

**Issue by gnouts** [erwindon/SaltGUI#265]
Hi,
I've tested SaltGUI for a couple hours and I didn't find a way to run orchestrators which is my main interest :)

The saltgui_template seems to support only `salt` command and not `salt-run`.

Is it possible to add orchestrator in template and manual run ?

**Comment by erwindon** [comment]
@gnouts 
The templating mechanism is "only" a mechanism to fill-in the fields from the "run" box.
Therefore the templating mechanism cannot pose a limitation by itself.

In my real-life orchestrators are not really needed; and no-one asked for it before; so therefore it was no explicitly added to SaltGUI.

`salt-run` commands are supported and they are identified by their prefix.
e.g. (from https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html)
`salt-run state.orchestrate orch.cleanfoo`
should be run as
`runners.state.orchestrate orch.cleanfoo`
in SaltGUI.

Let me know whether this is sufficient.
Is there anything that should be improved? e.g. the documentation?

**Comment by gnouts** [comment]
Thanks for the quick reply @erwindon !
That's exactly what I was looking for. I never made the link between salt-run and runners, which sounds obvious though... Thanks for the heads up ;) 

The UI is not very clean for runner though, but I guess it's Salt fault, not SaltGUI : 
* There is no color on the output.
* All the states of the orchestrator appear on the recent job list which is confusing.
* Also, once I closed the run box I'm unable to go back to the orginal "no color output". Showing the runner job is empty. I have to show all states, which is not very convenient to keep track of dependencies.

Here is what I mean : 
![2019-10-30_11h41_05](https://user-images.githubusercontent.com/17988185/67851381-a2bc3980-fb0a-11e9-8ea1-2ba8be04d1c7.png)

Maybe add to the documentation a short exemple like the one you give me. It definitely helped : 
> salt-run commands are supported and they are identified by their prefix.
e.g. (from https://docs.saltstack.com/en/latest/topics/orchestrate/orchestrate_runner.html)
salt-run state.orchestrate orch.cleanfoo
should be run as
runners.state.orchestrate orch.cleanfoo
in SaltGUI.

**Comment by erwindon** [comment]
* All the states of the orchestrator appear on the recent job list which is confusing.
This is the list of jobs as retrieved using `runners.jobs.list_jobs`.
I've added request #267 as an initiative to improve this. (but note that we may not find a useable solution)

* There is no color on the output
can you provide a sample output? and a description of what can be improved?
Please add this an a separate issue, so it can be tracked.

* once I closed the run box I'm unable to go back to the orginal "no color output". Showing the runner job is empty. I have to show all states, which is not very convenient to keep track of dependencies.
Unfortunately, I do not fully understand your remark (maybe I should set up a use-case with orchestration). Can you create a new issue for this situation?
The run-box is an overlay. It is hidden when you close it. The original jobs list that may be behind it is not updated in the mean time.

Documentation will be improved in #266

p.s. the "unknown-target" issue visible in your screenshot has been solved by a more recent `saltstack` release.

This issue is closed because new issues are created for the additional questions/remarks and the original issue has been explained.

**Comment by gnouts** [comment]
Thanks I'll create other issues as needed. :)
