### ISSUE TITLE
I am trying to use saltgui_preview_grains like "grain.get ip4_interfaces:eth1"

### ISSUE THREAD

**Issue by alexlllll** [erwindon/SaltGUI#273]
**Describe the bug**
I am trying to use saltgui_preview_grains like "grain.get ip4_interfaces:eth1" in the cli. But it doesnt work.

This doesnt work
```
saltgui_preview_grains:
    - ip4_interfaces:eth1
```
If I remove eth1, it works fine. Then I get all the ip's of every interface. But I just need to see that specific eth1 interface and not the rest. 

**To Reproduce**
```
[root@salt ~]# salt '*' grains.get ip4_interfaces:eth1

209.25x.22x.11x:
    - 10.12.1.18
```

/etc/salt/master
```
saltgui_preview_grains:
    - ip4_interfaces:eth1
```
Wont show anything in saltgui.

**Expected behaviour**
To show me the ip address of interface ipv4 ip like I would using:
```
salt '*' grain.get ip4_interfaces:eth1
```

**Comment by erwindon** [comment]
I disagree with the label "bug" :-) because showing a part of a grain was never intended functionality.
We are using `grains.items` to get all grains at once. Then we pick the selected values.
But the feature that you describe is an great improvement on that!
So, I've marked is as such.

**Comment by erwindon** [comment]
Alex,

The syntax from `grains.get` allows to retrieve only dictionary items with each step. As you showed in your example, that means that the value that will be shown is an array of IPv4 numbers.

I tried an experiment with `jsonpath` from https://www.w3resource.com/JSON/JSONPath-with-JavaScript.php. That provides us with a even more flexible way to retrieve details. e.g. using
`$.ip4_interfaces.eth0[0]` will show the first IPv4 number for the `eth0` interface.

I propose the following solution:
* when name starts with `$`, jsonpath is used to determine the value
* when the name contains ':', a hierarchical lookup is done to determine the value
* otherwise it is a simple dictionary lookup (which does not actually differ from the previous step)

is that a reasonable solution for this request?
feel free to suggest any improvement...

**Comment by alexlllll** [comment]
Hi Erwindon,

Thank you for the great tool and your idea on this "feature request" :). 
I very agree with your proposal. Its better than I had in mind!

**Comment by erwindon** [comment]
Thx for the compliment! Without the initial work from @oliverdunk and @maerteijn and the additional contributions from others we wouldn't be where we are now.

**Comment by erwindon** [comment]
I've added the new code to branch `graindetails`.
Usage instructions in file `README.md` have also been updated.
@alexlllll Can you please give it a try?

**Comment by erwindon** [comment]
@alexlllll were you able to give this a small test?

**Comment by erwindon** [comment]
merged
