### ISSUE TITLE
Proxy behind Apache

### ISSUE THREAD

**Issue by ggiesen** [erwindon/SaltGUI#279]
Do you have an example for proxying SaltGUI behind Apache. I've been banging my head against it for a little while.

I'd like Apache to proxy https://web.server.host/saltgui to http://127.0.0.1:3333. The closest I've gotten is to have it work, but unable to load any static content (images, css, etc).

**Comment by erwindon** [comment]
I've not used such setup with SaltGUI itself. But I've enough experience with such setups in other situations. Can you please add the relevant fragments of the {{httpd.conf}} or from any include file that you used here? So that I get even more insight in what is needed.

**Comment by ggiesen** [comment]
/etc/salt/master.d:

`rest_cherrypy:
  port: 3333
  host: 127.0.0.1
  disable_ssl: true
  app: /srv/SaltGUI/saltgui/index.html
  static: /srv/SaltGUI/saltgui/static
  static_prefix: /saltgui/static
  root_prefix: /saltgui`

/etc/httpd/conf.d/saltgui.conf:

`ProxyPreserveHost On

<Directory /srv/SaltGUI/saltgui/static/>
  Options Indexes FollowSymLinks MultiViews
  AllowOverride None
  Require all granted
</Directory>

<Location /saltgui>
  ProxyPassReverseCookiePath / /saltgui
</Location>

ProxyPass /saltgui http://127.0.0.1:3333/saltgui
ProxyPassReverse /saltgui http://127.0.0.1:3333/saltgui`

**Comment by erwindon** [comment]
You need to request the homepage as `/saltgui/` because the simple `/saltgui` is not picked up by the `ProxyPass` rule. A simple `Alias` should be able to take care of that.

The `app:` and `static:` entry in your master file use `SaltGUI`, which is unexpected.
When I removed that part, the url `/saltgui/` has the static content (HTML, JS, PNG and CSS) working.
But the API calls still fail.

In SaltGUI, the JS/PNG/CSS urls are always relative. So that keeps them working. But all the API calls and page aliases are absolute. An initial mechanism is present to cope with deviating API calls. I'll take this as a start to work on it to also give the page routing the same capabilities.
By quickly adjusting a bunch of URLs inside the code, a working SaltGUI could be produced.

**Comment by erwindon** [comment]
I've started a new branch `urls` in which the URL handling in SaltGUI will be generalized.
A configuration parameter `API_URL` (actually only a prefix) for the URL for salt-api was already present.
A new configuration parameter `NAV_URL` (prefix) for the page navigation will now be added.
The corresponding PR is #280.
I'm committing piece-by-piece.
Can you perform a test with your setup once that is done?

**Comment by erwindon** [comment]
The change is complete.
Are you able to test with your setup?

**Comment by ggiesen** [comment]
Yep, give me a day or two and I'll test on my end

**Comment by erwindon** [comment]
@ggiesen 
and... any luck? or likely more appropriate... did you have time for this?

**Comment by ggiesen** [comment]
Yep, I finally got it tested last night and it seems to work. Much appreciated
