### ISSUE TITLE
Show salt master's event bus

### ISSUE THREAD

**Issue by mchugh19** [erwindon/SaltGUI#283]
**Is your feature request related to a problem? Please describe.**
It would be really helpful to be able to view the salt master's event bus. 
https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#events

**Describe the solution you'd like**
A page to display the salt event bus. It'd be extra great if the display could be filtered to show/hide specific event matches

**Describe alternatives you've considered**
Other option is simply to display via cli: `salt-run state.event pretty=True`

**Comment by erwindon** [comment]
@mchugh19 (and @morsik)
Since SaltGUI is already subscribed to the event-bus, this is actually not a big thing.
Let's first design this...
* INFORMATION: events in Salt are volatile. you can catch an event for processing. there is no facility to retrieve/query missed events.
* it is a new page
* the "Recent Jobs" panel is NOT added as the dynamic nature of this screen would otherwise let users assume that the job list is also dynamically updated
* the menu item is called "events" and will be located in the menu-bar between "jobs" and "logout".
* the page will show the last 100 events; older events will be dropped from the gui
* a search field will always be visible. only matching items will be visible, BUT ALSO only matching items will be added
* the screen consists of a table with 3 columns: "Timestamp", "Tag" and "Data"
* Timestamp will be taken from field "_stamp". That field will be stripped from the event before display. Date part of the timestamp will not be shown because it is always "today". Time part will obey setting `saltgui_datetime_fraction_digits`.
* new rows will be added to the top (so rows in the table are pushed down)
* a start/stop button is added to the top of the screen. initially the event processing on this screen is in stopped state. when event processing is in stopped state, all new events are completely ignored.
anything important that I missed?

**Comment by mchugh19** [comment]
That sounds excellent! I think the start/stop button also helps to make clear that filtering will not show past events.

**Comment by erwindon** [comment]
deviations from the original plan:
* the search functionality that is already used in SaltGUI is very generic. at least for the first version, I will not touch that. This means that the search bar is initially not visible, and all events are initially included.
* the search functionality that is already used in SaltGUI is very generic. at least for the first version, I will not touch that. This means that all events will be added to the table. the search function is still applied. but when a new row is not selected, it still counts as one of the 100 allowed rows.

**Comment by mchugh19** [comment]
wow! You're quick! 
My use case in requesting this functionality was:

- view the event bus generally
- show specific events which kick off reactors
- view outcomes of states and orchestration jobs run by reactors

Sounds like the search functionality should work just fine, but it'd be great if that includes being able to search/filter on a few different event IDs for the uses listed above

**Comment by erwindon** [comment]
@mchugh19 
> wow! You're quick!
a mere coincidence of an easy change icw me having time for it.

> search
the current search facility reduces the table on a page to only the rows that somewhere contain the exact text from the search field. so it is a single string search (neither a regexp nor searching from a list of words).
But the good news is that the underlying library is supporting regular expression. So another feature request may be able to use that somehow (in which all pages will benefit from that).

**Comment by erwindon** [comment]
TODO (in order in which they will likely be done)
* ~~data column is not yet properly formatted for complex/nested data~~
* search condition is not applied in any way to new rows
* there is no start/stop button yet
* number of rows limited to 5

**Comment by erwindon** [comment]
@mchugh19 
I think the events-page is complete now.
Can you have a look at this?
The branch is `events`.
Please, keep the browser console visible to spot any internal problems.
Let me know when you spot any problems, down to any cosmetic issues.
@morsik: do you have the opportunity to test this also?

**Comment by mchugh19** [comment]
It's looking really good, but I'm having trouble with the filtering. 

Given event tags: `salt/wheel/something` and `salt/ret/1234/return`, it'd like to filter out the salt/wheel events. I think this could be a regex like `^((?!(salt\/wheel)).)*$` but that doesn't seem to work. If I understand this properly (https://github.com/erwindon/SaltGUI/blob/events/saltgui/static/scripts/Utils.js#L172) it appears that regex entries aren't possible as any non alpha numeric characters are escaped. Is there a way to filter on just tags and to show or hide based on multiple criteria?

**Comment by erwindon** [comment]
@mchugh19 
I've created a new issue #285 for the improvement of the search facility, so that it can be treated independently.
Is there anything that still must be done on this issue ("Show salt master's event bus") before it can be closed?

**Comment by mchugh19** [comment]
I think it's working well. This can be closed. Thanks!

**Comment by erwindon** [comment]
closing it before it is merged is a bad practice :-)
