### ISSUE TITLE
Better quoting rules / parameter input for running jobs

### ISSUE THREAD

**Issue by jfunnell** [erwindon/SaltGUI#298]
**Is your feature request related to a problem? Please describe.**
I messed up some job runs trying to run powershell scripts, resulting in some very strange errors..
I'm not clear on what SaltGUI's quoting rules are, they don't seem to be documented? Do single-quotes work at all? Do you escape with backslashes? Etc..

**Describe the solution you'd like**
I think I would prefer if the job runner could take a set of multiline key: value pairs instead of a single command line with shell-ish quotes. It would help a lot with large params as well.
If you have a yaml or toml-style parser that would work well with a textarea input. Otherwise you could have a dynamically-growing list of inputs if that's better?

**Describe alternatives you've considered**
I used salt-pepper for my needs, as my shell highlights the strings for me.

BTW, thanks so much for making this project. Our team wouldn't have so readily adopted salt if it wasn't for this UI <3

**Comment by erwindon** [comment]
> [...]thanks so much for making this project[...]
@oliverdunk started the project. @maerteijn improved it. I expanded it to cover more functions.

**Comment by erwindon** [comment]
The commandline is using JSON notation.
The command is a string and each of its arguments are a JSON object.
Additionally, every standalone word is considered to be a string, which usually saves a bit of typing.
It is using JSON because that is basically what the `salt-api` is using.
I'll review the documentation to make it more clear.
I'll look at your suggestions also.
(to be continued)

**Comment by erwindon** [comment]
@jfunnell 
The cmd-box in SaltGUI closely matches the `salt` command-line.
The `salt` command-line also takes json parameters.
Strangely enough, the output from the `salt` command-line is then in another format: the 'nested' format, a yaml-like notation.
SaltGUI, by default, sticks to the json output for consistency. But the default output can be changed to `nested` or `yaml`.
So SaltGUI matches mostly to how the command-line also behaves.
I currently see no real reason to build an additional input modus (and even less for having it replace the current one).

But adding an explanation on how this all works is a great addition.
Much is already available in the `README.md` file that comes with the sourcecode and can be viewed on the GitHub page. But it is time to show the details to the actual users.
See the new branch `cmdhelp`.
The help-text will be shown in the output panel.
See below for the text that was used.
Do you think the text is clear enough? Any changes/additions are welcome...

The current text is:
===========================
Target field

Entries that contain a @, (, ) or space are assumed to be a compound target selection. See [[Compound Targeting]].
Entries that contain a COMMA are assumed to be a list target selection. See [[List Targeting]].
Entries that start with a # are assumed to be a nodegroup target selection. See [[Nodegroup Targeting]].
Otherwise, the target is assumed to be a regular glob selection. See [[Globbing Targeting]].
The dropdown-box to the right of the field is automatically updated with the assumed target type. When you do not agree, it is possible to manually select a value. That value will then be left alone by the system. Note that the dropdown-box only contains the choice 'Nodegroup' when nodegroups are configured in the master file.
For wheel commands, the value of the target field is added to the commandline as the named variable 'match'. Wheel commands that do not use that parameter do not have a problem with that.
For runners commands, the value of the target field is can be left empty. Any value is silently ignored.
Command field

The command field is used to enter the command and its parameters. Double quotes (") are needed around each item that contains spaces, or when it is otherwise mistaken for a number, boolean, list or object.
Parameters in the form name=value are used to pass named variables. The same quoting rules apply to the value. The named parameters are used from left-to-right. Their actual position within the line is otherwise not important.
A help button is visible when the command field contains some text. It will issue a sys.doc (or runners.doc.wheel or runners.doc.runner) command for the current command. The sys.doc command will be targetted to the given minions when the target field is not empty. It will be targetted to all minions when it is empty. The runners.doc.wheel or runners.doc.runner will always run on the master. When answers from multiple minions are available from sys.doc, the first reasonable answer is used. Small variations in the answer may exist when not all minions have the same software version.
Run command button

The 'Run command' button starts the given command for the given minions.
A dropdown menu to the right of the button can be used to specify that the command must be run asynchronously. In that case the output consists only of a link to retrieve the actual output. When a command takes too long, the command window can be closed without waiting for the output. The Jobs page can then be used to find that command and watch its progress or results.

Output panel

When the output is recognized as output from (a command similar to) state.highstate, then the output is formatted for readability. e.g. durations shorter than 10 milliseconds are removed. On the same line as the minion name, a summary is shown in the form of coloured CIRCLE characters. There is one character for each state. When the circle has a double bar over/under it (it is always both) then the state reported that work was done and it may be interesting to see it. Clicking on a circle will scroll to the corresponding state output and shortly highlight it.
Clicking on any output will scroll back to the minion name.
When a minion has multiple lines of output, it can be collapsed.
===========================

**Comment by jfunnell** [comment]
The documentation additions are excellent, my only critique is that you might want to note that quotes can be escaped using `\"`
And .. what does `\\"` do? Escape the backslash? Or does it still escape the quote. Other than that it answers every question I had.

Re: Changing the input, I respectfully disagree with:
>SaltGUI matches mostly to how the command-line also behaves.

As that's not the case for quoting, which is completely up to the user's shell. My shell handles a variety of quoting constructs and makes it trivial to embed scripts into `cmd.shell` execution. 
I suggested a different input form to avoid quoting entirely, but would be happy with a simpler solution as long as it makes command runs easier.. Salt seems to appeal to python users, so would it be reasonable to support """...""" for more complex parameters?

**Comment by erwindon** [comment]
I'll keep this issue open to improve on the new online documentation. I'll certainly add a note on the quoting rules. Which btw are all handled by `JSON.parse` so there should be no real surprises there.

> Changing the input, I respectfully disagree with[...]
no problem. I meant the basic principles: one line and quotes to keep words together. the fact that the shell (sh/cmd) is not involved gives some more freedom as no quotes are required for objects and arrays. which is then simpler but obviously different.

> """" support
Can you please create a new issue for that?
When _you_ create the issue, github allows me to assign it back to you for questions/review/etc.

**Comment by jfunnell** [comment]
Done! #301 better describes the issue and possible solution, along with a simple sample for testing.

**Comment by erwindon** [comment]
documentation was added to the run-box
