### ISSUE TITLE
Large highstates seem to break the job page

### ISSUE THREAD

**Issue by Timbus** [erwindon/SaltGUI#306]
**Describe the bug**
Trying to fetch the output of a highstate with about 50 steps gives me the following error and stacktrace:
```
Uncaught (in promise) TypeError: change is null
    _addChangesInfo http://salt:3333/static/scripts/output/OutputSaltGuiHighstate.js:96
    getHighStateOutput http://salt:3333/static/scripts/output/OutputSaltGuiHighstate.js:197
    addResponseOutput http://salt:3333/static/scripts/output/Output.js:547
    _handleJobRunnerJobsListJob http://salt:3333/static/scripts/panels/Job.js:183
    onShow http://salt:3333/static/scripts/panels/Job.js:43
    promise callback*onShow http://salt:3333/static/scripts/panels/Job.js:42
    onShow http://salt:3333/static/scripts/pages/Job.js:16
    _showPage http://salt:3333/static/scripts/Router.js:320
    goTo http://salt:3333/static/scripts/Router.js:279
    Router http://salt:3333/static/scripts/Router.js:54
    <anonymous> http://salt:3333/static/scripts/index.js:5
    EventListener.handleEvent* http://salt:3333/static/scripts/index.js:5
```
I can only guess the data is too slow to load? Or perhaps there is a specific step causing the problem? I can't really tell unfortunately. It results in the output screen being blank, and I have to use pepper or the salt master to fetch the output.

I'd love to provide a test case but.. that's pretty difficult considering the size of the highstate and the large amount of company data in it. I might tweak some of the JS to see if it can be quick-fixed.

If there's any debugging I can do to help, let me know..

**Comment by erwindon** [comment]
Timbus,
thx for the report!
I do not think that the size of the answer is the cause. I suspect just a strange bit of data that is present. The test on line 86 tests whether an object is returned with the state differences. In JS, a null is also an object, so that one passes uncaught, causing the exception on line 96. Should be an easy fix.
Just to be sure, are you able to provide data from the salt api-call {{jobs.list_job}} in json format? Using the JID of a job that causes the problems. Either from you browsers development tools of from a salt command to get the job details. Feel free to remove any string content from it by replacing the string with "abc". Using my e-mail (saltgui@dondorp.com) is preferred as the data, even in that form, may be useful for others. I totally understand when even that is not possible, safety first!.

**Comment by erwindon** [comment]
I simulated a response and recreated the problem (quicker than expected)

**Comment by erwindon** [comment]
Tested all 3 representations (raw/standard/saltgui).
Only the "saltgui" specific representation had the problem.

**Comment by erwindon** [comment]
@Timbus
I just committed the simple fix.
never mind that test-data I asked.
can you please test with the new version and let me know the result?

**Comment by Timbus** [comment]
Oh wow, already.
Yeah I'll deploy it now and see how it goes

**Comment by Timbus** [comment]
Works perfectly! Guess it's just a faulty state. Probably one of my custom ones, now that I think about it..

Thanks so much yet again!
