### ISSUE TITLE
Implement User/Admin mode for the GUI

### ISSUE THREAD

**Issue by reiner1959-coder** [erwindon/SaltGUI#398]
Question: 
We are on the way to utilize that nice GUI to have a kind two modes like: 
1.) Admin mode -> here the admin could do everything. Also the features form the user mode. 
2.) User mode -> In the GUI it just shows/allows only actions for the current logged in system. From this mode we also want to show some specific SLS files we created on the master in order to deploy environments the user could select form the kind list. 
What do you think? 
Thanks for your support.

**Comment by erwindon** [comment]
Reiner,

SaltGUI already has 2 per-user permission systems.

1) using api permissions:
Your "Admin" mode is the default.
Your "User" mode would have users in a group with only the permissions on the needed salt-api calls.
See https://docs.saltproject.io/en/latest/topics/eauth/access_control.html for more details.
This mechanism also has the power to restrict parameters on each api call. because that is supported by the salt-api, it is automatically useable for SaltGUI.
This is a secure mechanism. Users cannot bypass their permissions.
SaltGUI may sometimes show an error message when it is not properly expecting failure on a specific api call. At the moment that this feature was added, I tested many combinations. I can and will correct this when this is reported as an issue.

2) using saltgui_pages setting in the master file (see SaltGUI documentation)
You can hide complete pages from view for certain users or groups.
This is not a secure mechanism. Users still have the full salt-api permissions, but just less pages are visible.

Additionally, SaltGUI has a way to predefine commands in the master file. The list of available commands is then available in the "run" box for use there. Users can modify the commands and all users have the same list.

If you apply any or all of the above 3 mechanisms, what functionality is then missing?
And also important, how secure must the mechanism be? Is this a usability feature, or a security feature?

**Comment by erwindon** [comment]
@reiner1959-coder 
can you please answer the follow-up questions that I included in my response?
thx!

**Comment by erwindon** [comment]
@reiner1959-coder
you did not answer the follow-up question
feel free to re-open this issue when you have that information
