### ISSUE TITLE
SaltGui Authentication

### ISSUE THREAD

**Issue by mdtabrezpasha** [erwindon/SaltGUI#416]
Hi, i am doing the SaltGui Config for first time, my setup is not able to authenticate on the web ui.  have followed the setup guide.  user 'saltuser' exists, but authentication failure on the the UI.

plz suggest fix.

**Comment by erwindon** [comment]
@mdtabrezpasha
without further details, it is hard to offer any help.
you seem to have the login-page and are able to provide credentials, so basic web-application has been set up fine.

can you use the "saltuser" account to login in a normal way on that machine?
this verifies that the user has been setup properly.

are the clocks of the machine that runs the browser and the machine that runs the salt-master + salt-api (roughly) synchronized?
when they are more than 12 hours out of sync with each other, you will be logged out immediately after login.
(this is so rare that I do not even warn for it in the documentation; but it has happened to me)

is there any relevant error/warning message present in the browser console?
a browser console is typically part of the developer tools as present in most browsers.

**Comment by mdtabrezpasha** [comment]
Hi, i am able to login using saltuser account on the local machine.. 
both salt-master + salt-api are running on the same machine.. so clock sync is not an issue.  
browser console just gives me authentication error.

**Comment by erwindon** [comment]
the clock issue was between the browser and saltmaster/saltapi. but you already ruled out this as a cause, because this would not result in an authentication error.

were saltmaster and saltapi both (re)started after the config file change?

did you add the `external_auth:` block to the `/etc/salt/master` file? (or only the `rest_cherrypy:` block)

anything relevant visible in the `master` or `api` log files?
