### ISSUE TITLE
option to only show failed jobs

### ISSUE THREAD

**Issue by xzenor** [erwindon/SaltGUI#420]
**Is your feature request related to a problem? Please describe.**
A way to just show the failed jobs would be so convenient

**Describe the solution you'd like**
a menu option or even just a simple checkbox for "show only failed jobs". If it could also be enabled with an addition to the url (like https://url:3333/#jobs&failed=1) that would be even more awesome but that might not be possible.

**Describe alternatives you've considered**
I can't think of another way... If there is one, let me know.

**Additional context**
If all you have is loads of successful jobs then the error gets lost. I want that error to be visible.

**Comment by erwindon** [comment]
An alternative might be to use the "Issues" screen.
It currently has 6 plug-ins: Beacons, JobsRunning, Keys, NotConnected, Schedules and State.
It is possible to add a next plug-in: "FailedJobs", which reports jobs with failures.
The main problem here is that one cannot "solve" a failed job.
i.e. you can re-run the job resulting in a new outcome, but the original job will remain failed.
Therefore a failed jobs will be reported again-and-again.
(actually that would happen also on the Jobs screen)

**Comment by xzenor** [comment]
I'm gonna think about your comments for a bit. The issues screen does sound like the best place for this but honestly I don't really get what it does now. All it shows me are the minions that aren't connected. I can see that in the minions screen a lot quicker so it's probably doing a lot more in the background.

**Comment by erwindon** [comment]
NotConnected minions is just one of the 6 categories that are inspected in the Issues screen:
- Beacons: that are disabled on either beacon-level or minion-level
- JobsRunning: jobs that are still running
- Keys: unaccepted keys
- NotConnected: not connected minions
- Schedules: that are disabled on either schedule-level or minion-level
- State: any failed states from "highstate" style jobs

It is basically a "todo" list for administrators that do not want to look at many screens to find what is broken, forgotten or accidently disabled.

**Comment by xzenor** [comment]
oh nice.. failed jobs would perfectly fit in there but I understand that it's a hard problem to fix....

**Comment by erwindon** [comment]
that brings me back to the performance problem.
jobs can only be inspected one-by-one, which is a limit from the salt-api.
(the job listing can retrieve all information at once, but that does not contain result information)
the application can only inspect like one (or just a few) jobs per second.
the jobs-page only looks up the details from the jobs that are "in view". is therefore seems to have a reasonable performance.
searching for failed jobs might be a very long process when we need to walk through hundreds of available jobs.
so, my prediction is that this function will be unusably slowwwww...
there is filtering possible on the job's command, but the user would have to answer that question first...

the additional problem is that there is no way to remove a failed job permanently from the output as because it is not possible to remove a job from the jobs database, nor is it possible to annotate a job. thus failed jobs would be reported again-and-again.

The best solution is to think in terms of "state" and not in terms of "commands".
see https://docs.saltproject.io/en/latest/topics/tutorials/starting_states.html
The state might depend on the effects of the original action, or the state may depend on the result-status of the original action.
When "states" are used, 2 optimisations are possible; and both are implemented in the Issues page:
* It is already known that only jobs with the `state.apply`, `state.highstate` or `state.sls_id` commands need to be inspected; and
* SaltGUI can stop looking when it has found enough information. typically the search is limited to only one (or a few) jobs, not the whole jobs history.

**Comment by xzenor** [comment]
I tried iterating through the jobs and getting `jobs.exit_success` of all the jobs in `jobs.list_jobs` (with Python) but it is indeed really really slow. I was kinda hoping for a solution to easily see whenever a scheduled package update or a scheduled state went wrong but I guess I need to do this with events and reactors.  
The joblist isn't right for this apparently. Not with the current api capabilities anyway.

**Comment by erwindon** [comment]
I know that other web-applications for saltstack are using a database stop store job results. That opens a path to select jobs based on their results. But for SaltGUI the original creators decided for an api-only approach, and I too agree with that.

When you are looking for a specific salt command, you can use the filter capability of `jobs.list_jobs` using something like `search_function='["pkg.install"]'`. See https://docs.saltproject.io/en/latest/ref/runners/all/salt.runners.jobs.html#salt.runners.jobs.list_jobs for more details.
In that case at least all other job types are quickly skipped.

For scheduled states, the "Issues" screen in SaltGUI might still also be useable, as it uses that same filter feature to select only the "state"-related commands.

**Comment by xzenor** [comment]
hm, and that doesn't work with the api I guess... Too bad. can;t use runner modules in SaltGUI either so can't make a template for it :(

**Comment by erwindon** [comment]
> can;t use runner modules in SaltGUI either so can't make a template for it :(

but you can use runner modules in SaltGUI...  just prefix the command with `runners.`
e.g. I just tried `runners.jobs.list_jobs search_function=["saltutil.find_job"]`
(also works for `wheel.`)
when using a `runners` command, the `Target` field will be ignored because these commands run local on the master
this is documented in the `README.md` file, but in the online help for the command-box it is not explicitly mentioned (opened #422 for this)

there's no reason why templates do not work for this (as the templates don't care about the strings that they fill in into the text fields)

**Comment by xzenor** [comment]
Oh wow. This cool :)  
I noticed the wheel thing when accepting keys so I tried `runner` instead of `runners` so that didn't work.

Thanks.

**Comment by erwindon** [comment]
is is `runners` in the official documentation, see https://docs.saltproject.io/en/latest/ref/runners/all/salt.runners.jobs.html
but I also fell into the same trap a few times.
I'll improve the command box by catching `runner.` and make a separate warning of this (opened #423 for that)

**Comment by xzenor** [comment]
No need to change the code just for my not-reading-documentation skills...

**Comment by erwindon** [comment]
I think there is nothing more to do for me for this issue.
(just correct me when I'm wrong!)

**Comment by xzenor** [comment]
Oh sorry. I forgot to close the issue. You're completely correct. No reason this needs to stay open
