### ISSUE TITLE
Export Job Results and Minion Grains

### ISSUE THREAD

**Issue by buffman23** [erwindon/SaltGUI#421]
Could you add a feature to download the results of a job and a feature to download minion grains?
I would like to be able to download the grains of my minions in JSON format.

**Comment by erwindon** [comment]
You can use the command-box (use the `(>_)` icon in the top-right corner.
Specify the minion-name (or just `*`), provide command `grains.items` and click `Run command`.
The output is already in JSON format.
(not a download, but the JSON is ready to be copied to the clipboard)

You can predefine this command as a "template" in the main configuration file for easier entry later.

Also, you can always use the traditional tools:
`sudo salt --out=json '*' grains.items`
and:
`sudo salt-run --out=json jobs.list_jobs`
and
`sudo salt-run --out=json jobs.list_job 20220215232656779091`

Adding a feature to download information might be a lot of work:
* it should be present on all screens
* it needs a lot of additional decisions when the screen shows information from multiple api calls. e.g. the main screen (Minions) uses at least `wheel.key.list_all`, `grains.items` and `wheel.minions.connected` to populate the main panel.

My first conclusion is that this is too much work given that there seem to be good alternatives.

**Comment by buffman23** [comment]
I like option (3) where there is a download link. I personally use the command line for SaltStack and am familiar with option (2), but I am setting up SaltGUI for another user who doesn't want to use the command line.

**Comment by erwindon** [comment]
this is the plan:
* adding a download menu-item in the "panel-menu" on the "job" page
the "job" page is not in the menu, but it is shown after a job has been selected from the "jobs" page
* adding a download menu-item in the "row-menu" on the "jobs" page
* adding a download link on the "command-box" popup-box
the link is on the first line of the output so that it is only shown when there is output
* the download is always representing the content of the response. e.g.: when a `test.ping` was sent to 3 minions, the to-be-download content is `{"x1": true, "x2": true, "x3": true}`.
* the content is formatted for readability, matching how the data was displayed
* the filename will be based on the job-id, e.g `saltgui-20220216234713207676-result.json`. the download from the command-box has no access to the job-id and is thus simpler, e.g. `saltgui-result.json`.
* the browser will arrange the actual download as usual

any remarks on that?

**Comment by erwindon** [comment]
addition:
Using the download on the output of `(>_)` is currently very difficult.
At no point in the program flow is the `jobid` available when running a command there. And that parameter is required to re-query the job result.
The `jobid` is available when the original request was made with the additional internal parameter `full_return` is added.
But in that case, the output format also changes.
So that must be carefully dealt with.

So, download from the command-box will at first not be added.
But download from jobs-overview or jobs-details should not be a problem.
Only after the proper introduction of the `full_return` parameter can de download on the command-box happen again.

**Comment by erwindon** [comment]
I produced some first HTML in the top-right corner of the output-panel:
<table><tr><td>
    <img src="https://user-images.githubusercontent.com/3663742/155041213-f98be56c-0d73-4002-a7bb-104cd88b96ee.png" />
</td></tr></table>

**Comment by erwindon** [comment]
@buffman23 
A first implementation has been created.
You can find it on branch `download`.

Can you please try it?
(note that it will likely not work in the older browser version that you reported in #417)
Do all 4 download-types provide correct information?
Is this style of output useable?

**Comment by erwindon** [comment]
I did not receive a response (see also the notes on #417).
Since the functionality is separate from everything else, I'll assume that my own testing was sufficient.

**Comment by erwindon** [comment]
merged
