### ISSUE TITLE
What are "eligible" jobs? --> update documentation

### ISSUE THREAD

**Issue by achimmihca** [erwindon/SaltGUI#433]
In the "jobs" tab, one can select

- Show first 50 jobs
- Show eligible jobs
- Show all jobs

Further, at the bottom it says: `50 jobs shown, 6670 jobs eligible, 11329 jobs present`

What are "eligible" jobs?
I did not find this term in SaltStack documentation.
I only notice that it seems to be roughly half of all jobs.

**Comment by erwindon** [comment]
Some jobs are filtered out because they are (usually) caused by SaltGUI itself (e.g. `grains.list`).
What remains are jobs that are 'eligible' for displaying.
But then we still have too many jobs to display, so we limit that to 50 jobs (fixed configuration)

The user has the freedom to lift one or both of these restrictions.

The amount of 'eligible' jobs depends highly on the usage pattern. Are there scheduled jobs? reactors? Or is it just a user browsing through the gui? or is the user also performing sysadmin tasks using salt and/or SaltGUI? etc.

**Comment by erwindon** [comment]
note that SaltGUI has 2 settings to (1) include or (2) exclude job types from the predefined logic.

**Comment by erwindon** [comment]
feel free to propose a different term, or even a different implementation...

**Comment by achimmihca** [comment]
Thanks! 
The term is ok.
Should be documented somewhere.

**Comment by erwindon** [comment]
> Should be documented somewhere.

Let's use this ticket for that!
