### ISSUE TITLE
How to install/run the GUI.

### ISSUE THREAD

**Issue by bsikar** [erwindon/SaltGUI#457]
**Is your feature request related to a problem? Please describe.**
Not exactly. 

**Describe the solution you'd like**
I dont know how to start the GUI, like I see the screenshots and I have read the documentation, but I am still a bit confused. Could you add a "How to start the GUI" section or an "Installation" section or something like that?

**Describe alternatives you've considered**
Just adding some more sections in the docs, I tried to look it up and use youtube, but I really havent found what to do.

**Additional context**
I am pretty sure this is on my end, but when I run the `/runtests.sh` script I get this:
```
Creating docker_saltmaster-local_1 ...
Creating docker_saltmaster-local_1 ... error

ERROR: for docker_saltmaster-local_1  Cannot start service saltmaster-local: driver failed programming external connectivity on endpoint docker_saltmaster-local_1 (7242a5f910692177a6175c8e04c501f00f8f01d68109794bf05108be0f351bfc): Error starting userland proxy: listen tcp4 0.0.0.0:4506: bind: address already in use

ERROR: for saltmaster-local  Cannot start service saltmaster-local: driver failed programming external connectivity on endpoint docker_saltmaster-local_1 (7242a5f910692177a6175c8e04c501f00f8f01d68109794bf05108be0f351bfc): Error starting userland proxy: listen tcp4 0.0.0.0:4506: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Going to remove docker_saltmaster-local_1
Removing docker_saltmaster-local_1 ... done
```
I am a bit confused because before running the script that port isnt being used, or at least I dont think it is
```
[I] ◆ SaltGUI git:(master) ❯❯❯ sudo netstat -tunlp                                                                                       13:51
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8388          0.0.0.0:*               LISTEN      2319/ss-server
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1208/systemd-resolv
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1226/cupsd
tcp6       0      0 ::1:8388                :::*                    LISTEN      2319/ss-server
tcp6       0      0 ::1:631                 :::*                    LISTEN      1226/cupsd
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1222/avahi-daemon:
udp        0      0 0.0.0.0:55641           0.0.0.0:*                           1222/avahi-daemon:
udp        0      0 127.0.0.53:53           0.0.0.0:*                           1208/systemd-resolv
udp        0      0 127.0.0.1:8388          0.0.0.0:*                           2319/ss-server
udp        0      0 0.0.0.0:631             0.0.0.0:*                           1292/cups-browsed
udp6       0      0 :::5353                 :::*                                1222/avahi-daemon:
udp6       0      0 ::1:8388                :::*                                2319/ss-server
udp6       0      0 fe80::f6a9:27be:e10:546 :::*                                1230/NetworkManager
udp6       0      0 :::43748                :::*                                1222/avahi-daemon:
[I] ◆ SaltGUI git:(master) ❯❯❯ docker images ls                                                                                          13:51
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
[I] ◆ SaltGUI git:(master) ❯❯❯ docker container ls                                                                                       13:52
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
[I] ◆ SaltGUI git:(master) ❯❯❯         
```

**Comment by erwindon** [comment]
> I tried to look it up and use youtube
Neither myself nor the previous maintainers of SaltGUI placed any videos there
As the current maintainer, I try to provide the proper documentation.

the docker directory is more for testing and trying as it the salt-master in the same docker-compose setup should not be used to manage your (or anyone's) minions.
the docker images from docker-hub are mainly for demonstration and testing and are rarely up-to-date with the latest source code.

not many people actually try the stuff in ./docker. that includes myself.

runtests.sh has a few minor problems as it tries to use an older JS version
and the old (and limited) regression tests seem to break now too.

but runtest.sh is wrapper script for multiple tests. and they might each have their specific problems. you are better off running the parts that are useful at that moment.
e.g. to run SaltGUI in docker, the only thing you need is the "docker-compose --file docker/docker-compose.yml up -d" command from line 39 of the script. And then point your browser to port 3333. login using salt/salt.

"address already in use" means that another program is using the same port number.
in this case that typically happens when you run salt-master on the host-computer and try to run a docker image that also tries to use the network ports from saltstack.
the docker version is mainly for people to do NOT have saltstack up-and running.
you should be able to successfully start the docker images after stopping salt-master and salt-api.

**Comment by bsikar** [comment]
Okay when I removed salt-master from my computer and reran `sudo docker-compose --file docker/docker-compose.yml up -d` (I needed sudo for whatever reason) everything worked great and I was able to experience a really nice demo. 

Now if I do have salt-master on my computer and I am connected to lets say 5 minions what should I do now? For instance, what command would i run (without using docker) to see the GUI and all of my minions/keys/etc?

**Comment by erwindon** [comment]
@bsikar 
to properly use docker, most docker installations require that a specific 'named pipe' can be accessed, and only users that are members of the group 'docker' and of course 'root' can do that. typically you would need to update the /etc/group file (using sudo) and make your user a member of group 'docker'. there are commands for that too, but for me editing one file is faster. after that change, you need to logout and login again. the docker commands should behave properly now.

the installation notes for SaltGUI are in README.md. it does not make sense to repeat that information here. saltstack comes with a program salt-api, that handles both the api for saltstack and it is a micro webserver. SaltGUI uses that webserver to show its pages. the SaltGUI pages use the salt api to login/logout and (once logged in) collect all kinds of information that is presented on the screen. please follow the installation notes in the manual.

initially, the new minions are not part of the salt-cluster. configuring the hostname of the salt-master on the minion's side is only half the job. you'll see that the main page of SaltGUI is empty. go to the Keys page and see that all of them are waiting to be accepted. The Keys page has commands for that on minion level and also on page level to handle all minions at once. the corresponding command is 'sudo salt-key'. once minions are accepted, they show up in the main screen. from there you can inspect grains, schedules, pillars and beacons. the corresponding command is 'sudo salt' or inspect and manage jobs (sudo salt-run).

SaltGUI is typically installed and used by those that are already using saltstack and want their job to be easier. the SaltGUI documentation does not try to explain the purpose and working of saltstack as that is assumed to be known.

**Comment by bsikar** [comment]
I think I didn't explain my problem that well, what I am trying to accomplish is the running of SaltGUI. I have many minions already and I want to just run SaltGUI, what im looking for is something like `npm run start` where it will start SaltGUI.

**Comment by bsikar** [comment]
That clears a lot of this up for me and probably others, thank you so much. I did have another question, I am looking at the docs and under [here](https://docs.saltproject.io/en/latest/topics/eauth/index.html#external-authentication-system-configuration) it says:
```
Note

The PAM module does not allow authenticating as root.
```
If I wanted the root user to be the one authenticating, is it possible to use a [group](https://docs.saltproject.io/en/latest/topics/eauth/index.html#groups)?
and do something like this:
```
external_auth:
  pam:
    root:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
    root%:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'

rest_cherrypy:
  port: 3333
  host: 0.0.0.0
  disable_ssl: true
  app: /srv/saltgui/index.html
  static: /srv/saltgui/static
  static_path: /static
```
For my purpose, the master will be running on a server and the server only has one user. The server will also only be accessed by those who are supposed to have access. This means that having only one user (root) is what we have been doing. I also want to know, how should I go about making the person authenticating in the GUI have full control over everything with salt? Like for example, is this all the access a user can get?
```
external_auth:
  pam:
    USER_NAME:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
```
or is there more settings or a better way?

**Comment by erwindon** [comment]
'root%' is indeed the group that root belongs to. buy you will always need to login as a user that is a member of the specified group. so that won't help.
it is easy to create a normal user account. so there should be little reason to use the root account.

> The server will also only be accessed by those who are supposed to have access. 

that still sound like more than one person. you should set up normal user accounts for each of them and just configure sudo to allow each of them to use sudo without password. note that you can never trust anyone to keep a shared password secret. this is already bad for a single machine, but allowing it in a saltstack installation expands that risk to all connected machines.

> Oh and 1 last thing, is the user and pass for SaltGUI the user and pass for the actual user on the machine

when you choose 'pam' (pluggable authentication method), it depends on what you configured in the PAM configuration files.
the default is to use the unix password file and/or unix goup file. see page https://docs.saltproject.io/en/latest/ref/auth/all/index.html for other authentication types. since PAM by itself also uses plugins (hence the name), there are some possibilities there too, see https://en.wikipedia.org/wiki/Linux_PAM

> Is this all the access a user can get?

The default configuration as documented is
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
this means that this saltapi user may use all regular commands, all runner commands, all wheel commands and all jobs command. there are no other categories. SaltGUI itself uses all kinds of commands to get all the needed information. and it has commands in its menus to change often used settings. additionally, you can manually give a regular salt command in the gui.
the security configuration as given to salt-api works for any salt command that SaltGUI produces. e.g. when you no longer allow the '@wheel' commands, it is impossible for SaltGUI to present you the information of the Keys page. I know that there are some SaltGUI users that replaced the list of salt commands under external_auth to include only selected read-only commands.

**Comment by bsikar** [comment]
Okay sweet, that clears everything up, thank you so much for explaining everything to me and for being fast and very descriptive with your replies :)
