### ISSUE TITLE
Time not matching the system timezone.

### ISSUE THREAD

**Issue by mdtabrezpasha** [erwindon/SaltGUI#522]
**Describe the bug**
The gui job's show time as per UTC clock instead of the local system clock.  our time zone is Asia/Calcutta, but we get American time stamp on all our salt jobs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change time zone on system
2. Execute any command from saltgui
3. check the job status.  Time stamp is always UTC and not the local timezone.

**Expected behaviour**
Complted jobs should show the time as per the local system timezone.

**Additional context**

**Comment by erwindon** [comment]
SaltGUI has no hard-coded timezone. any "American" timestamp is caused by using a server that has that timezone or a local browser that has that timezone.

you can change how SaltGUI displays (most) dates and times using parameter `saltgui_datetime_representation` in the master configuration file. see chapter `Time Representation` in the manual https://erwindon.github.io/SaltGUI/.

you can also inspect the current value by looking at the SaltGUI Options-page which is normally hidden.
use CTRL-CLICK on the SaltGUI logo (top-left of the window) to go there
you can even experiment with the different value, but changing settings in that screen is for the current session only

**Comment by erwindon** [comment]
ping!

**Comment by erwindon** [comment]
no reaction for more than one week.
please re-open when this is still an issue.

**Comment by mdtabrezpasha** [comment]
Hi Erwin,
               sorry for the late reply.  I did follow the documentation
and made the changes in the master file today.  I am getting the correct
time stamp now on the GUI.  Thanks so much for your help.


Warm Regards,
*Mohammed Tabrez Pasha*
Systems Engineer
SkyNet Systems
Ph:9480126313
