### ISSUE TITLE
Show pillar information

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#58]
Pillars are much like grains.
But grains are typically properties of an environment, and pillars are often security tokens.
I have a branch with the functionality for showing pillars, just like the grains.
But I made the pillar values are initially hidden, using 8 bullet characters, just like a typical password field.
A small eye-icon indicates that there is more to see. a mouseover reveals the text.
Any suggestions to do things differently?

![afbeelding](https://user-images.githubusercontent.com/3663742/46116234-4d24a780-c1fb-11e8-9e1c-b9565f27d993.png)

(p.s. obvious fake fonts used in the image...)

**Comment by maerteijn** [comment]
Can you show me an example json response of the api?

Can this be protected by a permission setting?

**Comment by erwindon** [comment]
sample output is just like the grains output (from `pillar.items`):
```
{
  "return": [
    {
      "hostname1": {"secret3": "text", "secret2": "text", "secret4": {"a": "b"}},
      "hostname2": {"secret1": "txt"}
    }
  ]
}
```
The pillars are name-value pairs with no restrictions on the values. grains are managed on the minions, but pillars are managed on the master (but still available for a targetted minion).

**Comment by erwindon** [comment]
> Can this be protected by a permission setting?
the pillar information is kept in a well protected directory on the minion.
but everyone that can execute `pillar.items` can retrieve the information.
the main purpose for pillars is to reference them in templates with state information.

The salt api can be restricted to certain command categories only. I have a separate branch for that.

Note that anyone can just execute "grains.items" and see the information with the traditional `SaltGui` or `salt` interfaces.

**Comment by maerteijn** [comment]
Direct Answer to your question: Just  show the bullet characters and when you hover / click on it, the pillar becomes visible. (Clicking instead of hover is something we need to fix in all other menu's as well as mobile devices don't have a hover event)

Some other comments:
I did some research on restricting some functionality as when we easily expose pillar information it would be something too easy to make mistakes with. (I know that you could run `pillar.items` already, but exposing it in a menu with a list makes it really easy to access sensitive information)

BTW, there are some existing issues with the wrong error codes with the salt api (https://github.com/saltstack/salt/issues/48703) but nothing we can't catch as we use the fetch api which is a promise where you could catch that.

Anywho, with the following configuration SaltGUI still works but you are not allowed to execute any command (except `grain.items` which you use to display the minions):
```
external_auth:
  pam:
    salt:
      - grains.*
      - '@runner'
      - '@wheel'
      - '@jobs'
```

We are then, however, allowed to accept / reject all keys. This is configurable like documented here:
https://github.com/saltstack/salt/issues/19732 but  I don't understand how it works yet :) (maybe you know).

A long story short: When adding pillar information we first need to:
- Update the README documentation with a sane default configuration with some restrictions
- Document how you can enable / disable restrictions (like keys / commands etc)
- Document that it's **really important to restrict access to saltgui**
- Adjust SaltGUI that it does not break when commands are not allowed (like the 500 error)

**Comment by erwindon** [comment]
The reason for using the icon is that hovering over an html object that changes size has al kinds of funny layout issues. But changing it to use only a simple click also solves that.
At least you seem to agree that hiding the values until the user really wants to see it is a good solution here.
I consider the question answered. but it may take a while before this becomes a PR due to the additional requirements.

**Comment by erwindon** [comment]
(sorry to update your comment, you just reference user 'wheel`...)

**Comment by erwindon** [comment]
The best I know of is https://docs.saltstack.com/en/latest/topics/eauth/index.html

**Comment by maerteijn** [comment]
Sorry wheel user 😄 

Ok, then I'll figure out how this works and do some work in a separate branch.

**Comment by maerteijn** [comment]
Could you add issues for the schedule views, grains edit and schedule edit so we can discuss the functionality before the pull requests? Would save me and you a lot of time I think.

**Comment by erwindon** [comment]
that is a great idea. so far I wanted to keep the number of active subjects limited and the attention focussed... creating issues now.

**Comment by maerteijn** [comment]
@erwindon  I've been working on some refactoring and error handling sot SaltGUI anticipates on when you disable some permissions or features (like wheels / runners or certain commands).

It's a work in progress (I need to fix some rough edges), but you can see it here: https://github.com/maerteijn/SaltGUI/compare/api-cleanup-error-handling?expand=1

The minimum configuration now required is:
```
external_auth:
  pam:
    salt:
      - grains.items
      - sys.doc
      - state.apply
```
This works out pretty well. I also splitted the api into a real api class and a commandbox class, and did some refactoring.

I'll work on this the following days, add documentation and then I'll send you a pull request. Then I will respond to all the other features you want to add: I think having error handling and permissions straight is something really important now.

**Comment by maerteijn** [comment]
See my comments on #56, I moved my comments about security to #30

**Comment by erwindon** [comment]
see #92
