### ISSUE TITLE
Commandbox should get its own route and page

### ISSUE THREAD

**Issue by maerteijn** [erwindon/SaltGUI#63]
Now it's somehow a strange thing inside of SaltGUI. It would make much more sense to create a own route / page for it as the functionality for it is growing.

**Comment by erwindon** [comment]
This would eliminate the problem of updating the underlying screen whenever a command is run in the commandbox. On the other hand, the commandbox is used for just these cases. e.g. accepting a key on the keys page, etc. you don't want to manually switch back each time to see what to do next (accepting the next key, applying the next state, etc). So, some kind of "go back" feature should remain. Maybe just the 'X' that is already on the current screen.
Interesting to know what the fate of the "green circle" will be...

**Comment by maerteijn** [comment]
I don’t understand what you mean with “you don’t want to manually switch back to see what yo do next”

**Comment by erwindon** [comment]
The new command-page is slightly different from other pages. This is because you want to go back to the location where you initiated the navigation to the command-page. With a popup-panel (like now) that function is done with the 'X' in the top-right corner. When it is a page, something similar must remain. It then does not 'close' the panel, but navigates to the previous page.

**Comment by maerteijn** [comment]
Ah yes, that is something you want  indeed. I'll try some things first to see if  this idea makes sense.

**Comment by maerteijn** [comment]
I'll leave it up to you to close this

**Comment by erwindon** [comment]
no better suggestions have popped up
