### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by artb1sh** [erwindon/SaltGUI#93]
No permission -- see authorization schemes
![image](https://user-images.githubusercontent.com/4118703/50216217-463ea880-0396-11e9-8278-47dc6d7a2aed.png)

**Comment by erwindon** [comment]
Viktor,
This error is raised when you open the first page of SaltGUI.
It tries to perform a first dummy API call to see whether there is a valid login-session.
That call fails because you are nog logged in yet.
At that point SaltGUI redirects to the login screen, and at the same time leaving this error message.
Although no actual error occurs, I'll try to reduce the error messages for this one...

**Comment by erwindon** [comment]
Fixed in #94.
@artb1sh can you see whether that works also for you?

**Comment by artb1sh** [comment]
@erwindon , good!
Thx!

**Comment by erwindon** [comment]
merged.
thx again for reporting!
